spring:
  datasource:
    url: jdbc:mysql://rm-2ze4137ud1qr72002ao.mysql.rds.aliyuncs.com/yfwj
    username: yfwj
    password: Lian8419
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
server:
  port: 8089

keycloak:
  realm: tt
  auth-server-url: http://127.0.0.1:8080/auth
  resource: test

